version: 0.0
os: linux
files:
  - source: /
    destination: home/ubuntu/repo/traceguard/
file_exists_behavior: OVERWRITE


hooks:
  AfterInstall:
    - location: script/deploy.sh
      runas: ubuntu
      timeout: 300
      allow_failure: false
      