version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20

  pre_build:
    commands:
      - echo Preparing Docker Compose...

  build:
    commands:
      - echo Building and testing containers...
      - echo "Making scripts executable"
      - chmod +x script/deploy.sh

artifacts:
  files:
    - '**/*'