services:
  db:
    image: postgres:17.0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: traceguard
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b '0.0.0.0'"
    volumes:
      - .:/traceguard
      - gem_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:12345@db:5432/traceguard
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - db
      - redis

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/traceguard
      - gem_cache:/usr/local/bundle
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:12345@db:5432/traceguard
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - app
      - redis

volumes:
  postgres_data:
  redis_data:
  gem_cache: