services:
        #db:
        #    image: postgres:17.0
        #    volumes:
        # - postgres_data:/var/lib/postgresql/data
        #    environment:
        #      POSTGRES_PASSWORD: 12345
        #      POSTGRES_USER: postgres
        # POSTGRES_DB: traceguard
        #    ports:
        #      - "5432:5432"

  redis:
    image: redis:7.4
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b '0.0.0.0' -p '3030' -e production "
    volumes:
      - .:/traceguard
      - gem_cache:/usr/local/bundle
    ports:
      - "3030:3030"
    environment:
      RAILS_ENV: production
      HOST: 127.0.0.1
      APP_URL: http://${HOST}:${PORT}
      DB_CONNECTION: psql
      DB_HOST: db-prd-02.aquila.com.br
      DB_PORT: 5432
      DB_USERNAME: master
      DB_PASSWORD: '4e21 215m'
      DATABASE: traceguard
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - redis

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/traceguard
      - gem_cache:/usr/local/bundle
    environment:
      RAILS_ENV: production
      # DATABASE_URL: postgres://master:4e21 215m@db:5432/traceguard
      DB_CONNECTION: psql
      DB_HOST: db-prd-02.aquila.com.br
      DB_PORT: 5432
      DB_USERNAME: master
      DB_PASSWORD: '4e21 215m'
      DATABASE: traceguard
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - app
      - redis

volumes:
        #  postgres_data:
  redis_data:
  gem_cache: