default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] %>     
  port: <%= ENV['DB_PORT'] || 5432 %>  

development:
  <<: *default
  database: traceguard

test:
  <<: *default
  database: traceguard_test

production:
  <<: *default
  database: <%= ENV['DATABASE'] %> 
  username: <%= ENV['DB_USERNAME'] %> 
  password: <%= ENV['DB_PASSWORD'] %> 